name: CI_PUSH[CORE]

on:
  push:
    branches-ignore:
      - 'main'
      - 'dev-core'
      - 'dev-experiment'
      - 'dev-torch'
    paths:
      - 'artifact-core/**'
  workflow_dispatch:

env:
  COMPONENT: artifact-core

jobs:
  ci_component:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          cd ${{ env.COMPONENT }}
          poetry install --with dev

      - name: Run Linting with Ruff
        run: |
          cd ${{ env.COMPONENT }}
          poetry run ruff check .

      - name: Run Unit Tests with Pytest
        run: |
          cd ${{ env.COMPONENT }}
          poetry run pytest

      - name: Build Package
        run: |
          cd ${{ env.COMPONENT }}
          poetry build
