name: CI_PUSH[DEV_EXPERIMENT]

on:
  push:
    branches:
      - 'dev-experiment'
  workflow_dispatch:

env:
  COMPONENT: artifact-experiment

jobs:
  ci_component:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install Dependencies
        run: |
          cd ${{ env.COMPONENT }}
          poetry install --with dev

      - name: Run Linting with Ruff
        run: |
          cd ${{ env.COMPONENT }}
          poetry run ruff check .

      - name: Run Unit Tests with Pytest
        run: |
          cd ${{ env.COMPONENT }}
          poetry run pytest

      - name: Build Package
        run: |
          cd ${{ env.COMPONENT }}
          poetry build
