name: SONAR[PR_DEV_TORCH]

on:
  pull_request:
    branches: [ dev-torch ]
    paths: [ 'artifact-torch/**' ]
  workflow_dispatch: {}

env:
  COMPONENT: artifact-torch
  PROJECT_KEY: vasileios-ektor-papoulias_artifact-torch

jobs:
  sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          cd "$COMPONENT"
          poetry install --with dev

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ${{ env.COMPONENT }}
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}